apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: ${{ values.name }}
  description: Flask application template for backstage
  tags:
    - python
    - flask
  annotations:
    backstage.io/techdocs-ref: value

spec:
  type: service
  lifecycle: production
  owner: group:default/team-payments
